[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/fcichos/website/source/Fnotebooks/L1/Lecture-1.ipynb)

## Variables and types

### Symbol names 

Variable names in Python can contain alphanumerical characters `a-z`, `A-Z`, `0-9` and some special characters such as `_`. Normal variable names must start with a letter. 

By convention, variable names start with a lower-case letter, and Class names start with a capital letter. 

In addition, there are a number of Python keywords that cannot be used as variable names. These keywords are:

    and, as, assert, break, class, continue, def, del, elif, else, except, 
    exec, finally, for, from, global, if, import, in, is, lambda, not, or,
    pass, print, raise, return, try, while, with, yield

Note: Be aware of the keyword `lambda`, which could easily be a natural variable name in a scientific program. But being a keyword, it cannot be used as a variable name.

### Assignment



The assignment operator in Python is `=`. Python is a dynamically typed language, so we do not need to specify the type of a variable when we create one.

Assigning a value to a new variable creates the variable:

In [1]:
# variable assignments
x = 1.0
my_variable = 12.2

Although not explicitly specified, a variable does have a type associated with it. The type is derived from the value that was assigned to it.

In [2]:
type(x)

float

If we assign a new value to a variable, its type can change.

In [3]:
x = 1

In [4]:
type(x)

int

If we try to use a variable that has not yet been defined we get an `NameError`:

In [5]:
print(y)

NameError: name 'y' is not defined

### Number types


Python allows as any programming language different types of variables. The type of a variable can be always accessed with the help of the *type()* command. 

#### Integers

Integers are 32 bit binary numbers and extend from -$2^{31}$ to $2^{31}$-1. Python treats numbers without a decimal point automatically as an integer.

In [9]:
# integer number
x = 1 
type(x)

int

#### Floating Point

Floating point values are values with a decimal point and go between $\pm 2\times 10^{-308}$ and $\pm 2\times 10^{308}$

In [6]:
# float variable
x= 3.141 

#### Complex Numbers

In [22]:
c=2+4j
type(c)

complex

Complex numbers have built in *accessors*. These accessors give for example access to the *real* and *imaginary* part of the complex number. 

In [23]:
r=c.real
print(r)

2.0


In [24]:
i=c.imag
print(i)

4.0


On the other side, one my also evaluate the complex conjugate of a complex number by one of those accessors. Note that this is provided by a function here, while the above real and imaginary part are values. The are some basic functions available, which act on complex numbers. More complex calculations are possible with functions built in to modules such as *cmath* or *numpy*.

In [25]:
c=(2+4j).conjugate()
print(c.imag)

-4.0


#### Type casting

In [16]:
x = 1.5

print(x, type(x))

1.5 <class 'float'>


In [17]:
x = int(x)

print(x, type(x))

1 <class 'int'>


In [18]:
z = complex(x)

print(z, type(z))

(1+0j) <class 'complex'>


In [19]:
x = float(z)

TypeError: can't convert complex to float

Complex variables cannot be cast to floats or integers. We need to use `z.real` or `z.imag` to extract the part of the complex number we want:

In [20]:
y = bool(z.real)

print(z.real, " -> ", y, type(y))

y = bool(z.imag)

print(z.imag, " -> ", y, type(y))

1.0  ->  True <class 'bool'>
0.0  ->  False <class 'bool'>


## Operators and comparisons

Most operators and comparisons in Python work as one would expect:

* Arithmetic operators `+`, `-`, `*`, `/`, `//` (integer division), '**' power


In [28]:
1 + 2, 1 - 2, 1 * 2, 1 / 2

(3, -1, 2, 0.5)

In [29]:
1.0 + 2.0, 1.0 - 2.0, 1.0 * 2.0, 1.0 / 2.0

(3.0, -1.0, 2.0, 0.5)

In [30]:
# Integer division of float numbers
3.0 // 2.0

1.0

In [31]:
# Note! The power operators in python isn't ^, but **
2 ** 2

4

Note: The `/` operator always performs a floating point division in Python 3.x.
This is not true in Python 2.x, where the result of `/` is always an integer if the operands are integers.
to be more specific, `1/2 = 0.5` (`float`) in Python 3.x, and `1/2 = 0` (`int`) in Python 2.x (but `1.0/2 = 0.5` in Python 2.x).

* The boolean operators are spelled out as the words `and`, `not`, `or`. 

In [32]:
True and False

False

In [33]:
not False

True

In [34]:
True or False

True

* Comparison operators `>`, `<`, `>=` (greater or equal), `<=` (less or equal), `==` equality, `is` identical.

In [35]:
2 > 1, 2 < 1

(True, False)

In [36]:
2 > 2, 2 < 2

(False, False)

In [37]:
2 >= 2, 2 <= 2

(True, True)

In [38]:
# equality
[1,2] == [1,2]

True

In [39]:
# objects identical?
l1 = l2 = [1,2]

l1 is l2

True

***
## Modules

<a name="modules"></a>
<a href="#top">Jump to top</a>

The Python computer language consists of a “core” language plus a vast collection of supplementary software that is contained in modules. Many of these modules come with the standard Python distribution and provide added functionality for performing computer system tasks. Other modules provide more specialized capabilities that not every user may want. You can think of these modules as a kind of library from which you can borrow according to your needs.

There is a python module for almost everything ranging from Mie Scattering calculations in physics to Natural Language Processing for computers.

The most important modules for this course will be

* [Numpy](http://docs.scipy.org/doc/numpy/reference/index.html) - a collection of functions for numbers and arrays
* [SciPy](http://docs.scipy.org/doc/scipy/reference/) - a collections of functions for scientific computing
* [MatPlotLib](http://MatPlotLib.sourceforge.net/) - a collection of functions for plotting 
* [SymPy](http://docs.sympy.org) - a module for symbolic calculations 

A more complete list of standard modules in the Python distribution can be found [here](https://docs.python.org/3/py-modindex.html) along with the explainations of the functions therein.

These and other modules can be imported with the 

*import* 

command. The import command can be used in different ways. The simplest usage is

In [33]:
import numpy

Then all of the functions of are available under the so called namespace *numpy*. A namespace separates the functions contained in the module from other modules by requiring a suffix to address these function. Using the methods in the module *numpy* as imported above, you need to supply the *numpy* suffix as follows:

In [34]:
numpy.sqrt(3)

1.7320508075688772

If not all of the functions of a module are needed, only certain functions may be imported by

In [35]:
from numpy import sqrt

This saves memory. In this case, the function *sqrt* has been imported only and is available without the namespace *numpy*.

In [36]:
sqrt(2)

1.4142135623730951

You may also give the *sqrt* function its own name by

In [37]:
from numpy import sqrt as my_sqrt

In [38]:
my_sqrt(3)

1.7320508075688772

To import all of the functions from a module without the namespace convention just type in:

In [39]:
from numpy import *

In [40]:
sin(3)

0.1411200080598672

To import a module using a different namespace use:

In [41]:
import numpy as np

In [42]:
np.sqrt(3)

1.7320508075688772

Please bear in mind, that namespaces are great to keep things seperately. You might accidentially define a function which overwrites a module function that has been imported without a namespace. It may be really a tough thing to debug your code then in larger programs. 

***
### Variables

<a href="#top">Jump to top</a>

Variables are names to store data. One can assign a value to a variable with the *=* operator and use this variable for further computation.

In [43]:
a=1.0

In [44]:
a*3

3.0

To find out about the type of a variable use the *type()* command. The type command can be very useful in cases you use more complex data structures such as *arrays* or *lists*. We will shortly talk about the type command usage again, if we address type casting.

In [45]:
type(a)

float

Python offers a lot of short hand notations doing even complex assignments and computations in one line of code. The code below offers the possibility to assign two values to two variables with one assignment operator. Python itself keeps track of all required memory allocation procedures, that you don't have to take care of memory issues.

In [46]:
a,b=[3,5]

Once you have assigned data to a variable, you also change this data during your computations.

In [47]:
a=a+3 # shall give 6 with the line above
a

6

***
### Scripts and Script Files

<a href="#top">Jump to top</a>

The Jupyter notebook allows you to use a single cell as a script, which performs a number of calculations. Such scripts may also be saved in a file and run from that file. Wihtin these scripts *#* denotes a comment.

In [48]:
# short script
a=4
b=3

c=a*b
print(c)

12


If ones saves these lines to a file (i.e. with name *script.py*) one can execute its content using the *run* command. Note that the current working directory (check with *pwd* and *ls*) has to be the directory which contains the file. You can outsource whole parts of you code this way and even create your own modules.

In [49]:
run script.py

ERROR:root:File `'script.py'` not found.


### Help!

<a href="#top">Jump to top</a>

Python has a built in help system, which is interactive and can be accessed with the *help()* command.

In [57]:
help()


Welcome to Python 3.7's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.7/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".



help>  



You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


***
### Data Types in Python

<a href="#top">Jump to top</a>

Now that we know a bit about the general use of Python, it's time to look at different data types we may find useful in our course. Besides the data types for the different number types mentioned above, there are also other types like **strings**, **lists**, **tuples**, **arrays** and **dictionaries**. There are usually a number of *methods* (functions) connected to each data type providing useful functions. We will not talk about these methods, except we need them. It is up to you to explore the internet a bit and search for suitable methods for your purpose.


**Strings** are lists of keyboard characters as well as other characters not on your keyboard. They are not particularly interesting in scientific computing, but they are nevertheless necessary and useful. Texts on programming with Python typically devote a good deal of time and space to learning about strings and how to manipulate them. Our uses of them are rather modest, however, so we take a minimalist’s approach and only introduce a few of their features.

**Lists** are another data structure, similar to NumPy arrays, but unlike NumPy arrays, lists are a part of core Python. Lists have a variety of uses. They are useful, for example, in various bookkeeping tasks that arise in computer programming. Like arrays, they are sometimes used to store data. However, lists do not have the specialized properties and tools that make arrays so powerful for scientific computing. So in general, we prefer arrays to lists for working with scientific data. For other tasks, lists work just fine and can even be preferable to arrays.

**Tuples** are also list, but immutable. That means, if a tuple has been once defined, it cannot be changed. Try to change an element to see the result.

**Arrays** An array is a basic structure type of NumPy and the workhorse for most python calculations. The array defined in the numpy module is called ndarray in NumPy documentation and is similar to a list but with all the elements of the list are of the same type. An array of floats can for example store a whole measurement such as the intensity of a spectrum at different wavelenth or the velocity of a car at different time instances.

**Dictionaries** are like lists, but the elements of dictionaries are accessed in a different way than for lists. The elements of lists and arrays are numbered consecutively, and to access an element of a list or an array, you simply refer to the number corresponding to its position in the sequence. The elements of dictionaries are accessed by “keys”, which can be either strings or (arbitrary) integers (in no particular order). Dictionaries are an important part of core Python. However, we do not make much use of them in this introduction to scientific Python, so our discussion of them is limited.

The follwing few cells will give you a short introduction into each type. 

***
#### Strings
<a href="#top">Jump to top</a>

Strings are lists of characters, which are created with the help of single or double quotes. They belong to the sequence data type like lists or tuples. They can be assigned to variables.

In [58]:
s='Hello' # string variable

In [59]:
t="World!"

String can be concatenated using the *+* operator. 

In [60]:
c=s+' '+t

In [61]:
print(c)

Hello World!


As strings are lists, each character in a string can be accessed by addressing the position in the string (see Lists section)

In [62]:
c[1]

'e'

Strings can also be made out of numbers.

In [63]:
"975"+"321"

'975321'

If you want to obtain a number of a string, you can use what is known as type casting. Using type casting you may convert the string or any other data type into a different type if this is possible. To find out if a string is a pure number you may use the str.isnumeric() method. For the above string, we may want to do a conversion to the type *int* by typing:

In [64]:
("975"+"321").isnumeric() # or you may use as well str.isnumeric("975"+"321")

True

In [65]:
int("975"+"321")

975321

There are a number of methods connected to the string data type. Usually the relate to formatting or finding sub-strings. Formatting will be a topic in our next lecture. Here we just refer to one simple find example.

In [66]:
t.find('ld') ## returns the index at which the sub string 'ld' starts in t

3

In [67]:
t.capitalize()

'World!'

****
### Lists

<a href="#top">Jump to top</a>

Lists are sequences of one or more elements. The elements of lists can be numbers or strings, or both at the same time. Lists are defined by a pair of square brackets on either end with individual elements separated by commas. Here are two examples of lists:

In [68]:
a = [0, 1, 1, 2, 3, 5, 8, 13]

In [69]:
b = [5., "girl", 2+0j, "horse", 21]

The length of a list can be obtained by the *len()* command if you need the number of elements in the list for your calculations.

In [70]:
len(b)

5

There are powerful ways to iterate through a list and also through arrays in form of *iterator*. We will talk about them later in more detail. Here is an example, which shows the powerful options you have in Python. The example will go through the list **b** and return all elements of the type str. 

In [71]:
[element for element in b if type(element)==str]

['girl', 'horse']

Individual elements in a list can be accessed by the variable name and the number (index) of the list element put in square brackets. Note that the index for the elements start at *0* for the first element (left). 

In [72]:
b[1]

'girl'

Elements may be also accessed from the back by nagative indices. *b[-1]* denotes the last element in the list and *b[-2]*, the element before the last.

In [73]:
b[-1]

21

In [74]:
b[-2]

'horse'

Individual elements in a list can be replaced by assigning a new value to them

In [75]:
b[-2]='cat'

In [76]:
b

[5.0, 'girl', (2+0j), 'cat', 21]

Lists can be concatanated by the *+* operator

In [77]:
c=a+b
c

[0, 1, 1, 2, 3, 5, 8, 13, 5.0, 'girl', (2+0j), 'cat', 21]

A very useful feature for lists in python is the **slicing** of lists. Slicing means, that we access only a range of elements in the list, i.e. element 3 to 7. This is done by inserting the starting and the ending element number separated by a colon (:) in the square brackets. The index numbers can be positive or negative again.

In [78]:
c[3:7]

[2, 3, 5, 8]

Inserting a second colon behind the ending element index together with a thrid number allows even to select only ever second or third element from a list.

In [79]:
c[3:9:2]

[2, 5, 13]

Lists may be created in different ways. An empty list can be created by assigning emtpy square brackets to a variable name. You can append elements to the list with the help of the append command which has to be added to the variable name as shown below. This way of adding a particular function, which is part of a certain variable class is part of object oriented programming.

In [80]:
a=[]

In [81]:
a.append('h')

A list of numbers can be easily created by the *range()* command.

In [82]:
range(10)

range(0, 10)

In [83]:
range(3,10)

range(3, 10)

In [84]:
range(3,10,2)

range(3, 10, 2)

Lists (and also tuples below) can be multidimensional as well, i.e. for an image. The individual elements may then be addressed by supplying two indices in two square brackets.

In [85]:
a = [[3, 9], [8, 5], [11, 1]]

In [86]:
a[1]

[8, 5]

In [87]:
a[1][0]

8

****
#### Tuples
<a href="#top">Jump to top</a>

Tuples are also list, but immutable. That means, if a tuple has been once defined, it cannot be changed. Try to change an element to see the result.

In [88]:
c = (1, 1, 2, 3, 5, 8, 13)

****
#### Arrays
<a href="#top">Jump to top</a>

The NumPy array is the real workhorse of data structures for scientific and engineering applications. The NumPy array, formally called ndarray in NumPy documentation, is similar to a list but where all the elements of the list are of the same type. The elements of a NumPy array, or simply an array, are usually numbers, but can also be boolians, strings, or other objects. When the elements are numbers, they must all be of the same type. For example, they might be all integers or all floating point numbers. For numpy array's we need to import the NumPy module.

In [89]:
import numpy as np

In [90]:
#this is a list
a = [0, 0, 1, 4, 7, 16, 31, 64, 127]

In [91]:
type(a)

list

In [92]:
#this creates an array out of a list
b=np.array(a)

In [93]:
type(b)

numpy.ndarray

The *linspace* function creates an array of N evenly spaced points between a starting point and an ending point. The form of the function is linspace(start, stop, N).If the third argument N is omitted,then N=50. *logspace* is doing equivelent things with logaritmic spacing. Other types of array creation techniques are listed below. Try around with these commands to get a feeling what they do.

In [94]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [95]:
np.logspace(1, 3, 5)

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

In [96]:
np.arange(0, 10, 1.5)

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [97]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [98]:
np.ones(8, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1])

All kinds of mathematica operations can be carried out on arrays. Typically these operation act element wise as seen from the examples below.

In [99]:
a=np.arange(0, 10, 1.5)
a

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [100]:
a/2

array([0.  , 0.75, 1.5 , 2.25, 3.  , 3.75, 4.5 ])

In [101]:
a**2

array([ 0.  ,  2.25,  9.  , 20.25, 36.  , 56.25, 81.  ])

In [102]:
np.sin(a)

array([ 0.        ,  0.99749499,  0.14112001, -0.97753012, -0.2794155 ,
        0.93799998,  0.41211849])

In [103]:
np.exp(-a)

array([1.00000000e+00, 2.23130160e-01, 4.97870684e-02, 1.11089965e-02,
       2.47875218e-03, 5.53084370e-04, 1.23409804e-04])

In [104]:
(a+2)/3

array([0.66666667, 1.16666667, 1.66666667, 2.16666667, 2.66666667,
       3.16666667, 3.66666667])

Operation between multiple vectors allow in particular very quick operations. The operations address then elements of the same index. These operations are called vector operations since the concern the whole array at the same time. The product between two vectors results therefore not in a dot product, which gives one number but in an array of multiplied elements. 

In [105]:
a = np.array([34., -12, 5.])
b = np.array([68., 5.0, 20.])

In [106]:
a+b

array([102.,  -7.,  25.])

In [107]:
a*b

array([2312.,  -60.,  100.])

In [108]:
a*np.exp(-b)

array([ 9.98743918e-29, -8.08553640e-02,  1.03057681e-08])

**Slicing** of arrays works the same way as for lists and can be very useful to vectorize calculations as shown in the example below. Here the position $y$ of an object has been measured at times $t$ and stored in an array each. We wish to calculate the average velocity at the times $t_{i}$ from the arrays by


\begin{equation}
v_{i}=\frac{y_i-y_{i-1}}{t_{i}-t_{i-1}}
\end{equation}


This can be done by slicing the arrays as displayed below. Find out, why the sling starts or stops at $1$ or $-1$.

In [109]:
y = np.array([ 0. , 1.3, 5. , 10.9, 18.9, 28.7, 40. ])
t = np.array([ 0. , 0.49, 1. , 1.5 , 2.08, 2.55, 3.2 ])

In [110]:
v = (y[1:]-y[:-1])/(t[1:]-t[:-1])

In [111]:
v

array([ 2.65306122,  7.25490196, 11.8       , 13.79310345, 20.85106383,
       17.38461538])

Multidimensional arrays can be created in python as well. There are again different ways to do that. Play around with the examples and search for other variants as well.

In [112]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [113]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [114]:
a=np.zeros(9)

In [115]:
a.reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

****
#### Dictionaries
<a href="#top">Jump to top</a>

A Python list is a collection of Python objects indexed by an ordered sequence of integers starting from zero. A dictionary is also collection of Python objects, just like a list, but one that is indexed by strings or numbers (not necessarily integers and not in any particular order) or even tuples! For example, suppose we want to make a dictionary of room numbers indexed by the name of the person who occupies each room. We create our dictionary using curly brackets {...}.

In [116]:
room = {"Ralf":422, "Frank":322, "Dekan":550}

In [117]:
room['Ralf']

422

In [118]:
room.keys()

dict_keys(['Ralf', 'Frank', 'Dekan'])

In [119]:
room.values()

dict_values([422, 322, 550])

***
## What's next

This has been a short overview over the basic things in Jupyter and Python. We will address more details on the way to our physical problems and data analysis code. As one of the most fundamental features required in physics is plotting of data, we will address plotting with a first primer next week in Lecture 2. Also input and output including keybord and files will be of our concern. 